name: CI-master

on:
    push:
        branches: [master]

jobs:
    test:
        name: Jest
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: Setup Node.js environment
              uses: actions/setup-node@v2.5.1
              with:
                  node-version: 17

            - name: install dependencies
              run: yarn install

            - name: initialize environments
              run: |
                  echo "NOTION_TOKEN=${{ secrets.NOTION_TOKEN }}" >> $GITHUB_ENV
                  echo "DB_ID=${{ secrets.DB_ID }}" >> $GITHUB_ENV

            - name: Jest Unit test
              run: yarn test
